### ISSUE TITLE
NullPointerException:invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()

### ISSUE THREAD

**Issue by rickyyikai** [gavinliu/ShapedImageView#13]
Sometimes I get crash report from Crashlytics. 
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference
       at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:69)
       at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:226)
       at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:82)
       at cn.gavinliu.android.lib.shapedimageview.ShapedImageView.onDraw(ShapedImageView.java:130)
       at android.view.View.draw(View.java:21860)
       at android.view.View.updateDisplayListIfDirty(View.java:20733)
       at android.view.View.draw(View.java:21586)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
       at android.view.View.draw(View.java:21863)
       at android.view.View.updateDisplayListIfDirty(View.java:20733)
       at android.view.View.draw(View.java:21586)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
       at android.view.View.updateDisplayListIfDirty(View.java:20719)
       at android.view.View.draw(View.java:21586)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
       at android.view.View.draw(View.java:21863)
       at android.view.View.updateDisplayListIfDirty(View.java:20733)
       at android.view.View.draw(View.java:21586)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
       at android.view.View.updateDisplayListIfDirty(View.java:20719)
       at android.view.View.draw(View.java:21586)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
       at android.view.View.draw(View.java:21863)
       at android.view.View.updateDisplayListIfDirty(View.java:20733)
       at android.view.View.draw(View.java:21586)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
       at android.view.View.updateDisplayListIfDirty(View.java:20719)
       at android.view.View.draw(View.java:21586)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
       at android.view.View.updateDisplayListIfDirty(View.java:20719)
       at android.view.View.draw(View.java:21586)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
       at android.view.View.updateDisplayListIfDirty(View.java:20719)
       at android.view.View.draw(View.java:21586)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
       at android.view.View.updateDisplayListIfDirty(View.java:20719)
       at android.view.View.draw(View.java:21586)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
       at android.view.View.draw(View.java:21863)
       at com.android.internal.policy.DecorView.draw(DecorView.java:1083)
       at android.view.View.updateDisplayListIfDirty(View.java:20733)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:725)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:731)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:840)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:3932)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3706)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3014)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1873)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8478)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
       at android.view.Choreographer.doCallbacks(Choreographer.java:761)
       at android.view.Choreographer.doFrame(Choreographer.java:696)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:6986)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

**Comment by gavinliu** [comment]
Thanks for your feedback, You can upgrade to 0.8.9

```
implementation 'cn.gavinliu:ShapedImageView:0.8.9'
```

Fix Commit

https://github.com/gavinliu/ShapedImageView/commit/ecd495a601dfc981ed811a070ce87fed55991f78
https://github.com/gavinliu/ShapedImageView/commit/333be6bf5e86926ecb2045bfc52b6032c470f625

**Comment by rickyyikai** [comment]
Thank you very much~!
